import CoFooter from "@/compnents/footer";
import CoHeader from "@/compnents/header";
import CoOurServices from "@/compnents/our-services";
import CoService from "@/compnents/service";
import CoSubmitApplication from "@/compnents/submit-application";
import MoHeaderLink from "@/molecules/header-link";
import Head from "next/head";
import headerPhoto from '../assets/multimodal-cargo-header.webp';
import photo1 from '../assets/multimodal-cargo-1.webp';
import photo2 from '../assets/multimodal-cargo-2.webp';
import photo3 from '../assets/multimodal-cargo-3.webp';

function Aviaperevozki() {
    return (
        <>
            <Head>
                <title>Transline</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <CoHeader />
                <CoService
                    MoBlockHeader="Мультимодальные перевозки"
                    HeaderPhoto={headerPhoto}
                    MoNavLinkerText2="Мультимодальные перевозки"
                    MoNavLinkerLink2="/multimodalnye-gruzoperevozki"

                    Photo1={photo1} Photo2={photo2} Photo3={photo3}

                    BoxHeader1="Наши услуги по мультимодальным перевозкам"
                    BoxDesc1={[
                        `Самолеты, поезда, грузовики и корабли. Иногда для удовлетворения ваших потребностей требуется их комбинация.`,
                        `Наличие различных видов транспорта позволяет нам адаптировать логистическое решение в соответствии с вашим бюджетом и графиком.`,
                        `Например, наше решение по перевозке морским транспортом может быть на 80% быстрее, чем морские перевозки, при незначительной стоимости авиаперевозок.`,
                        `У нас работают профессиональные команды, обеспечивающие бесперебойную передачу грузов между видами транспорта.`,
                        
                    ]}
                    BoxHeader2="Типы и размеры грузов"
                    BoxPreDesc2 = "Объединение нескольких видов транспорта означает, что, как правило, могут быть отправлены грузы практически любого размера, конфигурации и типа. При использовании воздушного транспорта в ваших решениях для модальных перевозок будут существовать некоторые ограничения."
                    BoxDesc2={[
                        // 'Вино и алкоголь',
                        // 'Товары для дома',
                        // 'Сталь и промышленные изделия',
                        // 'Развешивание одежды',
                        // 'Автомобильная',
                        // 'Скоропортящиеся товары с регулируемой температурой',
                        // 'Быстро перемещающиеся потребительские товары',
                        // 'Печатные СМИ',
                        // 'Опасные грузы',
                        // 'Оборудование и материалы для горных работ',
                        // 'Вторсырье',
                        // 'Хрупкие и чувствительные грузы',
                    ]}
                    BoxPostDesc2="Мы можем разработать мультимодальное решение в соответствии с вашими потребностями."
                    BoxHeader3="Почему выбирают нас?"
                    BoxPreDesc3="У нас есть множество услуг, чтобы предложить нашим клиентам наилучшее решение. Помимо мультимодального транспортного маршрута, адаптированного к вашим потребностям, вы можете рассчитывать:"
                    BoxDesc3={[
                        'Стыковка для полной и частичной погрузки',
                        'Складирование',
                        'Дистрибуция',
                        'Услуги по подбору и упаковке',
                        'Мультимодальные транспортные услуги, включая автомобильные, воздушные и морские',
                    ]}
                    BoxPostDesc3='Мы перевозили грузы практически любого размера, конфигурации и типа – расскажите нам о своих требованиях, и мы будем работать с вами, чтобы удовлетворить ваши потребности.'
                />
                <CoOurServices withoutHeader/>
                <CoSubmitApplication />
                <CoFooter />
            </main>
        </>
    )
}
export default Aviaperevozki;