import CoFooter from "@/compnents/footer";
import CoHeader from "@/compnents/header";
import CoOurServices from "@/compnents/our-services";
import CoSubmitApplication from "@/compnents/submit-application";
import MoHeaderLink from "@/molecules/header-link";
import Head from "next/head";
import MoNavLinker from "@/molecules/nav-linker";
import MoBlockHeader from "@/molecules/block-header";
import KontaktyIntro from "@/compnents/kontakty-intro";

function Kontakty() {
    return (
        <>
            <Head>
                <title>Transline</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <CoHeader />
                
                <div style={{marginTop: '188px'}}>
                    <MoBlockHeader text="Контакты" />
                    <MoNavLinker text2="Контакты" />
                </div>
                <KontaktyIntro/>
                <CoSubmitApplication />
                <CoFooter />
            </main>
        </>
    )
}
export default Kontakty;