import Head from 'next/head'
import CoFooter from "@/compnents/footer";
import CoHeader from "@/compnents/header";
import ServicesIntro from '@/compnents/services-intro';

export default function Services() {
    return (
        <>
            <Head>
                <title>Услуги Transline</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <CoHeader />
                <ServicesIntro />
                <CoFooter />
            </main>
        </>
    )
}